#pragma once
#include "config_common.h"

#define COMBO_COUNT 4

#define NO_MUSIC_MODE

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE

#define CIRQUE_PINNACLE_TAP_ENABLE
#define CIRQUE_PINNACLE_POSITION_MODE CIRQUE_PINNACLE_ABSOLUTE_MODE 
#define CIRQUE_PINNACLE_ATTENUATION EXTREG__TRACK_ADCCONFIG__ADC_ATTENUATE_3X

#define POINTING_DEVICE_GESTURES_SCROLL_ENABLE 
#define POINTING_DEVICE_GESTURES_CURSOR_GLIDE_ENABLE
