name: Build QMK firmware
on:
  push:
    branches:
      - main
      - master
      - 'develop**'
jobs:

  Build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix: 
        - keyboard: bad_wings
          maintainer: jasonhazel
          keymap: default
        - keyboard: dust
          maintainer: jasonhazel
          keymap: default
    steps:
      - name: Checkout QMK
        uses: actions/checkout@v3
        with:
          # change this to your repo
          repository: jasonhazel/qmk_hazel
          submodules: recursive

      
      - name: Build firmware
        run: |
          
          make ${{ matrix.maintainer}}/${{ matrix.keyboard}}:${{ matrix.keymap }}

      - name: Archive firmware
        uses: actions/upload-artifact@v3
        continue-on-error: true
        with:
          name: firmware
          path: |
            *.hex
            *.bin
            *.uf2

